"""Changed username to user_id in User model

Revision ID: 5dced98284eb
Revises: 9e2ef753b57f
Create Date: 2024-05-17 14:45:41.143831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5dced98284eb'
down_revision = '9e2ef753b57f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.String(length=64), nullable=True))
        batch_op.drop_index('ix_user_username')
        batch_op.create_index(batch_op.f('ix_user_user_id'), ['user_id'], unique=True)
        batch_op.drop_column('username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.VARCHAR(length=64), nullable=True))
        batch_op.drop_index(batch_op.f('ix_user_user_id'))
        batch_op.create_index('ix_user_username', ['username'], unique=False)
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
