"""Added classroom_id to User and relationship to Classroom

Revision ID: 9e2ef753b57f
Revises: 196b4d0aa558
Create Date: 2024-05-17 14:22:46.959526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e2ef753b57f'
down_revision = '196b4d0aa558'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('classroom_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_user_classroom', 'classroom', ['classroom_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('classroom_id')

    # ### end Alembic commands ###
